<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
    xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
    xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
    xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
    xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
    xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
    xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ns0="http://xmlns.vs.nl/fuse/demo/xsd/AnimalOrders"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
    exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source
                type="WSDL">
                <oracle-xsl-mapper:schema
                    location="../Schemas/AnimalOrders.xsd" />
                <oracle-xsl-mapper:rootElement
                    name="animalOrderRequest"
                    namespace="http://xmlns.vs.nl/fuse/demo/xsd/AnimalOrders" />
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target
                type="XSD">
                <oracle-xsl-mapper:schema
                    location="../Schemas/AnimalOrders.xsd" />
                <oracle-xsl-mapper:rootElement
                    name="animalOrderResponse"
                    namespace="http://xmlns.vs.nl/fuse/demo/xsd/AnimalOrders" />
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) 
            AT [TUE NOV 24 15:38:37 CET 2020]. -->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE -->
    <xsl:template match="/">
        <ns0:animalOrderResponse>
            <ns0:animalOrder>
                <ns0:customer>
                    <xsl:if
                        test="/ns0:animalOrderRequest/ns0:animalOrder/ns0:customer/@id">
                        <xsl:attribute name="id">
                     <xsl:value-of
                            select="/ns0:animalOrderRequest/ns0:animalOrder/ns0:customer/@id" />
                  </xsl:attribute>
                    </xsl:if>
                    <ns0:name>
                        <xsl:value-of
                            select="/ns0:animalOrderRequest/ns0:animalOrder/ns0:customer/ns0:name" />
                    </ns0:name>
                    <ns0:city>
                        <xsl:value-of
                            select="/ns0:animalOrderRequest/ns0:animalOrder/ns0:customer/ns0:city" />
                    </ns0:city>
                    <ns0:country>
                        <xsl:value-of
                            select="/ns0:animalOrderRequest/ns0:animalOrder/ns0:customer/ns0:country" />
                    </ns0:country>
                </ns0:customer>
            </ns0:animalOrder>
        </ns0:animalOrderResponse>
    </xsl:template>
</xsl:stylesheet>